# Generated by Django 3.1.6 on 2021-04-18 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_cutomer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cutomer',
        ),
    ]
